### A Verbose Tutorial: Local Natural Language Processing Linear Descriminant Analysis (or Principle Component Analsys) from NPLIA or "NLP In Action" (by Hobbson Lane), using podman and offical TensorFlow Container with Jupyter Notebook

## For Podman tensorflow env:

Assuming podman is installed:
https://podman.io/getting-started/installation

Run in terminal to create your containerized tensorflow friendly python environmnet complete with jyputer. 

```
$ podman pull tensorflow/tensorflow:latest 
$ podman run -it -p 8888:8888 tensorflow/tensorflow:latest-jupyter
```
Note: If prompted, selecting the docker tensorflow package may work.

In [3]:
# Upgrade pip
!python -m pip install --upgrade pip

     |████████████████████████████████| 2.1 MB 1.8 MB/s eta 0:00:01
  Attempting uninstall: pip
    Found existing installation: pip 20.2.4
    Uninstalling pip-20.2.4:
      Successfully uninstalled pip-20.2.4


In [6]:
# Install NLPIA
!python -m pip install nlpia

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 32.0/32.0 MB 15.8 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.5/109.5 kB 12.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 20.5 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/6.7 MB 21.0 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 588.3/588.3 MB 3.3 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 706.6/706.6 kB 44.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.2/15.2 MB 19.1 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 293.3/293.3 kB 22.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 14.8 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 840.9/840.9 kB 20.5 MB/s eta 0:00:0000:01
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.2/112.2 kB 17.0 MB/s eta 0:00:00
     ━━━━

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 18.4 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 kB 6.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 492.6/492.6 kB 19.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 181.6/181.6 kB 21.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 18.7 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.8/130.8 kB 16.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 828.9/828.9 kB 21.7 MB/s eta 0:00:0000:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.1/67.1 kB 9.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 18.3 MB/s eta 0:00:0000:010:01


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.1/78.1 kB 11.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.2/78.2 kB 11.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done


  Created wheel for future: filename=future-0.18.3-py3-none-any.whl size=492025 sha256=af689dffecb8231bac749163173d8285deb8c3be36516cf2fc8c73776726f3e1
  Stored in directory: /root/.cache/pip/wheels/a0/0b/ee/e6994fadb42c1354dcccb139b0bf2795271bddfe6253ccdf11
  Created wheel for fst-pso: filename=fst_pso-1.8.1-py3-none-any.whl size=20430 sha256=cba67e9728c9e93b73c1ca7dc58420a8a8505f8d024b24bd8e9b9bb6a4bbc89c
  Stored in directory: /root/.cache/pip/wheels/6a/65/c4/d27eeee9ba3fc150a0dae150519591103b9e0dbffde3ae77dc
  Created wheel for miniful: filename=miniful-0.0.6-py3-none-any.whl size=3513 sha256=4924a1268c0e413f0e86c9593332afde5befceab49963bc52fb05c0dd7de9cd1
  Stored in directory: /root/.cache/pip/wheels/ba/d9/a0/ddd93af16d5855dd9bad417623e70948fdac119d1d34fb17c8
Successfully built future fst-pso miniful
  Attempting uninstall: nbformat
    Found existing installation: nbformat 4.4.0
    Uninstalling nbformat-4.4.0:
      Successfully uninstalled nbformat-4.4.0


In [8]:
# !python -m pip install scikit-learn

In [7]:
# import your python libraries
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize.casual import casual_tokenize

In [24]:
# set display
pd.options.display.width = 120

In [9]:
# get training data
from nlpia.data.loaders import get_data

/usr/local/lib/python3.8/dist-packages/pugnlp/constants.py:136: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  [datetime.datetime, pd.datetime, pd.Timestamp])
/usr/local/lib/python3.8/dist-packages/pugnlp/constants.py:158: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  MIN_TIMESTAMP = pd.Timestamp(pd.datetime(1677, 9, 22, 0, 12, 44), tz='utc')
/usr/local/lib/python3.8/dist-packages/pugnlp/tutil.py:100: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead.
  np = pd.np
/usr/local/lib/python3.8/dist-packages/pugnlp/util.py:80: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead.
  np = pd.np
/usr/local/lib/python3.8/dist-packages/nlp

In [25]:
sms = get_data('sms-spam')

In [26]:
# What kind of object is 'sms'?
type(sms)

pandas.core.frame.DataFrame

In [27]:
sms

spam                                               text
0        0  Go until jurong point, crazy.. Available only ...
1        0                      Ok lar... Joking wif u oni...
2        1  Free entry in 2 a wkly comp to win FA Cup fina...
3        0  U dun say so early hor... U c already then say...
4        0  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
4832     1  This is the 2nd time we have tried 2 contact u...
4833     0               Will ü b going to esplanade fr home?
4834     0  Pity, * was in mood for that. So...any other s...
4835     0  The guy did some bitching but I acted like i'd...
4836     0                         Rofl. Its true to its name

[4837 rows x 2 columns]

In [28]:
# fod display: flag spam messages with '!' a bang label
index = ['sms{}{}'.format(i, '!'*j) for (i,j) in\
        zip(range(len(sms)), sms.spam)]

In [29]:
# make your custom-indexed version of the sms dataframe
sms = pd.DataFrame(sms.values, columns=sms.columns, index=index)

In [30]:
sms

spam                                               text
sms0        0  Go until jurong point, crazy.. Available only ...
sms1        0                      Ok lar... Joking wif u oni...
sms2!       1  Free entry in 2 a wkly comp to win FA Cup fina...
sms3        0  U dun say so early hor... U c already then say...
sms4        0  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
sms4832!    1  This is the 2nd time we have tried 2 contact u...
sms4833     0               Will ü b going to esplanade fr home?
sms4834     0  Pity, * was in mood for that. So...any other s...
sms4835     0  The guy did some bitching but I acted like i'd...
sms4836     0                         Rofl. Its true to its name

[4837 rows x 2 columns]

In [31]:
"""
The 'spam' column of the 'sms' dataframe should be an integer (1 or 0),
that indicates the class of the message (the label of the dataset):
1 -> spam
0 -> ham (not-spam)

For good measure:
Force type of 'spam' column to be int
"""
sms['spam'] = sms.spam.astype(int)

In [32]:
# get length of dataset...length of a dataframe??
len(sms)

4837

In [33]:
# shape of dataset (more normal way to do it....maybe)
sms.shape

(4837, 2)

In [34]:
# what portion of the training data is spam?
sms.spam.sum()

638

In [37]:
# Tokenize your language data:
tfidf_model = TfidfVectorizer(tokenizer=casual_tokenize)

In [39]:
tfidf_docs = tfidf_model.fit_transform( raw_documents=sms.text ).toarray()

In [41]:
# now let's look at the shape of the array of tokens:
tfidf_docs.shape

(4837, 9232)

In [50]:
tfidf_docs

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
"""
LDA time:
- find the vector-space centroid of your two classes:
1. spam
2. ham (not_spam)
"""

In [42]:
mask = sms.spam.astype(bool).values

In [43]:
spam_centroid = tfidf_docs[mask].mean(axis=0)

In [44]:
ham_centroid = tfidf_docs[~mask].mean(axis=0)

In [47]:
# inspection
spam_centroid

array([0.06377591, 0.0041675 , 0.00056204, ..., 0.        , 0.        ,
       0.        ])

In [45]:
# view as two-decimals
spam_centroid.round(2)

array([0.06, 0.  , 0.  , ..., 0.  , 0.  , 0.  ])

In [46]:
# view as two-decimals
ham_centroid.round(2)

array([0.02, 0.01, 0.  , ..., 0.  , 0.  , 0.  ])

### Overview:
If this is a linear model, then we will be able to draw a line that separates the two classes. (Hotdog, not_hotdog)

Now that we have calculated centroids for the vector regions of the two classification-classes we are trying to distinguish from one-another:

Simply subtraction one centroid from the other should give us the 'line' or linear model separating the two classes:

How many centroids are there?

In [48]:
spam_centroid.shape

(9232,)

In [49]:
ham_centroid.shape

(9232,)

There are as many centroids as there are columns:
in a transverse kind of day, each centroid is the mean of an entire  column. 

The get the line between the centroids we use the dot-product. 
(is that subtraction?)


In [51]:
spam_score = tfidf_docs.dot(spam_centroid - ham_centroid)

In [52]:
spam_score

array([-0.01469806, -0.02007376,  0.03856095, ..., -0.01014774,
       -0.00344281,  0.00395752])

In [53]:
spam_score.round(2)

array([-0.01, -0.02,  0.04, ..., -0.01, -0.  ,  0.  ])

In [58]:
# !python -m pip install open3d

points = spam_score

import open3d as o3d

pcd = o3d.geometry.PointCloud()

pcd.points = o3d.utility.Vector3dVector(points)
pcd.colors = o3d.utility.Vector3dVector(colors/65535)
pcd.normals = o3d.utility.Vector3dVector(normals)

o3d.visualization.draw_geometries([pcd])

In [59]:
# train a model on your centroids

from sklearn.preprocessing import MinMaxScaler

In [60]:
sms['lda_score'] = MinMaxScaler().fit_transform(spam_score.reshape(-1,1))

sms['lda_predict'] = (sms.lda_score > .5).astype(int)

### Predict and Score just the first 6:

In [63]:
sms['spam lda_predict lda_score'.split()].round(2).head(6)

spam  lda_predict  lda_score
sms0      0            0       0.23
sms1      0            0       0.18
sms2!     1            1       0.72
sms3      0            0       0.18
sms4      0            0       0.29
sms5!     1            1       0.55

## Predict and Score (all examples)

In [67]:
(1. - (sms.spam - sms.lda_predict).abs().sum() / len(sms)).round(3)

0.977

# Confusion Matrix

In [68]:
from pugnlp.stats import Confusion

/usr/local/lib/python3.8/dist-packages/pugnlp/stats.py:25: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead.
  np = pd.np


In [69]:
Confusion(sms['spam lda_predict'.split()])

/usr/local/lib/python3.8/dist-packages/pugnlp/stats.py:504: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.__setattr__('_hist_labels', self.sum().astype(int))
/usr/local/lib/python3.8/dist-packages/pugnlp/stats.py:510: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  setattr(self, '_hist_classes', self.T.sum())
/usr/local/lib/python3.8/dist-packages/pugnlp/stats.py:513: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  setattr(self, '_tp', self.get(self._pos_label, pd.Series()).get(self._pos_label, 0))
/usr/local/lib/python3.8/dist-packages/pugnlp/stats.py:517: FutureWarning: The default dtype for empty Series will be 'object' instead of 'f

lda_predict     0    1
spam                  
0            4135   64
1              45  593